# This is a basic workflow to help you get started with Actions

name: Compile and Verify

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
      
      # Runs a single command using the runners shell
      - name: Compile LaTeX documents
        uses: xu-cheng/latex-action@v3
        with:
          root_file:
            thesis.tex
            abstract-cs.tex
            abstract-en.tex

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: PDF
          path: |
            thesis.pdf
            abstract-cs.pdf
            abstract-en.pdf
    
  verify:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: PDF

      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.github_token }}        

      - name: Pull verapdf docker image
        run: docker pull ghcr.io/mff-cuni-cz/cuni-thesis-validator:latest
      
      - name: Verify Thesis pdfa compatibility
        run: |
          docker run -v $PWD:/thesis ghcr.io/mff-cuni-cz/cuni-thesis-validator verify /thesis/thesis.pdf | tee /dev/stderr | grep 'isCompliant="true"'
      - name: Verify EN Abstract pdfa compatibility
        run: |
          docker run -v $PWD:/thesis ghcr.io/mff-cuni-cz/cuni-thesis-validator verify /thesis/abstract-en.pdf | tee /dev/stderr | grep 'isCompliant="true"'
      - name: Verify CS Abstract pdfa compatibility
        run: |
          docker run -v $PWD:/thesis ghcr.io/mff-cuni-cz/cuni-thesis-validator verify /thesis/abstract-cs.pdf | tee /dev/stderr | grep 'isCompliant="true"'
